//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEvaluation
    {
        public Nullable<int> evalid { get; set; }
        public Nullable<int> courseid { get; set; }
        public Nullable<int> studentid { get; set; }
        public Nullable<int> obtainmarks { get; set; }
        public Nullable<int> grade { get; set; }
        public int Id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Evaluation Evaluation { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Student Student { get; set; }
    }
}
