//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacherattendence
    {
        public Nullable<int> AttendenceID { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> status { get; set; }
        public int Id { get; set; }
    
        public virtual Attendence Attendence { get; set; }
        public virtual Lookup Lookup { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
